########################################################################################################################
#                                                       JAVA DEV                                                        #
########################################################################################################################
FROM maven:3.6.1-jdk-8 as JAVA_DEV

########################################################################################################################
#                                                       JAVA BUILDER                                                       #
########################################################################################################################
FROM JAVA_DEV as JAVA_BUILDER

WORKDIR /opt

# TAG mavenjdk/java:latest

RUN git clone https://github.com/wangcaihua/angel-acumos.git
RUN cd angel-acumos && mvn -e -B clean package -Dmaven.test.skip=true
RUN apt-get update && apt-get install -y dos2unix
RUN cd angel-acumos && dos2unix run.sh

########################################################################################################################
#                                                       Runtime                                                        #
########################################################################################################################
FROM openjdk:8-jre as Runtime

# TAG runtime/jre:latest
RUN mkdir -p /opt/angel-acumos && mkdir -p /opt/models

ENV ANGEL_ACUMOS=/opt/angel-acumos

WORKDIR $ANGEL_ACUMOS

COPY --from=JAVA_BUILDER /opt/angel-acumos/target/acumos-*-assembly.jar .
COPY --from=JAVA_BUILDER /opt/angel-acumos/run.sh .
COPY --from=JAVA_BUILDER /opt/angel-acumos/models ./models/

ENV PATH="$ANGEL_ACUMOS:${PATH}" \
    GRPC_PORT=8500 \
    HTTP_PORT=8501 \
    MODEL_BASE_PATH=${ANGEL_ACUMOS}/models/fm

EXPOSE 8500 8501

VOLUME /opt/models

CMD [ "/bin/sh", "./run.sh" ]
