########################################################################################################################
#                                                       JAVA DEV                                                        #
########################################################################################################################
FROM maven:3.6.1-jdk-8 as JAVA_DEV

########################################################################################################################
#                                                       JAVA BUILDER                                                       #
########################################################################################################################
FROM JAVA_DEV as JAVA_BUILDER

WORKDIR /opt

RUN git clone https://github.com/wangcaihua/angel-acumos.git
RUN cd angel-acumos && mvn -e -B clean package -Dmaven.test.skip=true

########################################################################################################################
#                                                       Runtime                                                        #
########################################################################################################################
FROM openjdk:8-jre as Runtime

ENV ANGEL_ACUMOS=/opt/angel-acumos

COPY --from=JAVA_BUILDER /opt/angel-acumos/target/acumos-*-assembly.jar ANGEL_ACUMOS
COPY --from=JAVA_BUILDER /opt/angel-acumos/run.sh ANGEL_ACUMOS
COPY --from=JAVA_BUILDER /opt/angel-acumos/models ANGEL_ACUMOS/models

WORKDIR ANGEL_ACUMOS

ENV PATH="$ANGEL_ACUMOS:${PATH}" \
    GRPC_PORT=8500 \
    HTTP_PORT=8501 \
    MODEL_BASE_PATH=${ANGEL_ACUMOS}/models/fm

EXPOSE 8500 8501

VOLUME /models

CMD [ "/bin/sh", "./run.sh" ]
